### PR TITLE
Feature/issue89

### PR DESCRIPTION
**Pull request by daveneti**
Finally fixed the issues with quotes. Single and double quotes can be used in names and is provided they are not at the start and end. In this case they are removed and and delimiters inside are ignored.

### CODE REVIEW

**Comment by hdbeukel** [comment]
I am having issues to read this kind of data into R. There doesn't seem to be an easy way to allow quotes within text values, unless the entire string is also quoted (using the other quote character). Any reason for not imposing this within Core Hunter?

**Comment by daveneti** [comment]
quotes are only needed if a token contains the delimiter. The option was looking at was using an escape character, but I did not go that route. Let me check the code again.

**Comment by hdbeukel** [comment]
If you have an idea about how to get R to understand this same format, that would probably be the best solution. Haven't found anything yet though.

**Comment by hdbeukel** [comment]
R also doesn't seem to like escape characters for quotes...

**Comment by daveneti** [comment]
Only if the option REMOVE_QUOTES is set does it treat the quotes are important. But I think CH does this. Is it an R issue? I am not really sure what the problem is?

**Comment by hdbeukel** [comment]
Yes this is an R issue. But I don't currently know how to resolve it, apart from restricting the data format in Java too so that R can also understand it.

An example:

```
ID     , NAME   , mk1, mk2, mk3, mk4, mk5, mk6, mk7
"Ali,ce"  , 'Alice', 1  , 0  , 2  , 1  , 1  , 0  , 0
Unkn"own,        , 2  , 0  , 2  , 0  , 1  , 2  , 1
Bob-1  , Bob    , 1  , 0  ,    , 0  , 1  , 1  , 0
"Bob'-2"  , Bob    , 1  , 0  , 1  , 1  , 1  , 2
"Car'ol", 'Car,ol'  , 1  , 0  ,    , 0  ,    , 2  , 0
```

Here R fails on `Unkn"own` because it contains a quote. It does accept `'Unkn"own'`. Your code accepts both, but I can't get R to accept the former. So there are two solutions:

  1. Only allow `'Unkn"own'`, not `Unkn"own`, even though your code can read both.
  2. Try to find a solution in R, but that seems to be hard.

What do you suggest?

**Comment by hdbeukel** [comment]
Can you point me to the file and line where you deal with these quotes in the library? I couldn't find any built-in function in R, nor any library, that can read the data as is. So either I have to parse manually (as you do in Java, but I would rather not in R) or we impose the restriction for Core Hunter that names/ids containing `"` should be quoted with `'` and vice versa.

**Comment by daveneti** [comment]
https://github.com/unoinformatics/informatics-common/blob/develop/informatics-utils/src/main/java/uno/informatics/common/io/text/TextFileRowReader.java#L623-L656 creates the regex pattern based on the options. With REMOVE_QUOTES (needs a better name, perhaps PARSE_QUOTES) it has 4 groups. 1 for single quotes, 1 for double quotes, 1 for unquoted, and 1 for the special case at the end of the line. If you can't find an R solution, I suggest you impose the restriction for CH as you describe. My R skills are not good enough to understand the issue in R. Is there no option to 'escape' a quote in R?

**Comment by hdbeukel** [comment]
Thanks. I did not find a solution in R, so (at least for now) I will impose the restriction. I added instructions for using quotes on the data file format page on the website. See http://www.corehunter.org/data.

**Pull request merged**
