### PR TITLE
Feature/new write methods

### PR DESCRIPTION
**Pull request by daveneti**

### CODE REVIEW

**Comment by daveneti** [comment]
@hdbeukel can you please check this merge. I have added another writeData method to each Data class that takes a solution to subset the data. I also create a new class SimplePhenotypeData to extend ArrayFeatureData.

**Comment by hdbeukel** [comment]
I will check in detail later but one question: would it not be better to not duplicate the write code? I understand the new write method has the ability to produce exactly the same output format but restricted to the selected items. So why not delegate the original write method to the new method with all IDs selected?

**Comment by daveneti** [comment]
Yes, I totally agree, it usally best not to duplicate code if needed. I did this time because I did not want to disturb the original code and because the new code may not be as efficient since it needs to check if an id is selected or not, and it outputs in the order determined by the solution and not the order in the dataset.

**Comment by hdbeukel** [comment]
Ok I see. Is it really that important though for the write methods to be maximally efficient? Their implementation is quite technical so I still think we should avoid duplication even when trading for efficiency here. I will review your changes in detail now, do you agree that I merge both write methods?

**Comment by daveneti** [comment]
Yes, we can merge the method.

**Comment by daveneti** [comment]
In the case of full dataset, yes it should be the in order given by the ids from getIds() method. I am happy to do the coding if you like,

**Comment by hdbeukel** [comment]
And why not also when writing a subset?

**Comment by daveneti** [comment]
Yes, I think that is what it does now.

**Comment by hdbeukel** [comment]
Btw, `getIDs()` returns a `HashSet` so there is no order there. I don't see the point of following this order. I guess what the user expects is that the rows are ordered the same as in the input file, which means according to increasing ID as the IDs are assigned consecutively. So I guess you should sort the IDs when writing a subset.

I also think you can avoid converting the set of all IDs to an `ArrayList` and using `indexOf`. This is the main bottleneck for efficiency. I believe it's sufficient to 

1. Retrieve the set of IDs you want to include in the output (all, selected, unselected).
2. Convert these to an `ArrayList`.
3. Iterate over the `ArrayList` and write in this order. You can directly use the IDs as indices in the data structures (rows).

I have some time now to do a further review. Let me try to merge and optimize efficiency, ok?

**Comment by hdbeukel** [comment]
The alternative for sorting when writing would be to store the IDs in a `TreeSet` but that may slow down the optimization so I prefer sorting when writing.

**Comment by daveneti** [comment]
I agree :) This was one of the reason I asked you to check, because I was not 100% sure on this issue.

**Comment by daveneti** [comment]
I am not going to do anything now, its too late. So if you like and have time you can do it today (my night), otherwise I will pick it up tomorrow (your night). That is the good thing about being 12 different :)

**Comment by hdbeukel** [comment]
Good, I will get my hands on it.

**Comment by hdbeukel** [comment]
I have only managed to merge in `SimpleBiallelicGenotypeData`. Not added any tests yet but the tests that were already in place for the main write method still succeed and thus now also cover part of the subset write method.

If you want you can go on with the other data classes and I will review and pick up tomorrow.

**Comment by daveneti** [comment]
Ok, please go ahead, I am going to work on informatics-common instead.

**Comment by hdbeukel** [comment]
I have completed the review and merge for all data classes and it should be well tested. For phenotypes I was not able to merge the two write methods since the general one is in informatics-commons and the subset one is in Core Hunter.

One question though. For the default genotype data format it is currently only possible to write to frequency format, not the original format. Wouldn't users expect to be able to write to the original format?

**Pull request merged**
