### PR TITLE
Allow to set seed

### PR DESCRIPTION
**Pull request by hdbeukel**
**TODO**: make seed generator setting of engine (`CoreHunter`) instead of problem (`CoreHunterArguments`).

### CODE REVIEW

**Comment by daveneti** [comment]
Commits now merged to develop. @hdbeukel can we close this issue now, or is there further work to be done?

**Comment by hdbeukel** [comment]
I guess the seed generator should be an option in `CoreHunter` rather than `CoreHunterArguments` (see TODO above). As far as I can see, the latter contains settings defining the problem (data, obj, size) while the former provides options to tune the search (e.g. stop conditions). If we follow this logic, the seed generator (which tunes the search, not the problem) should be an option of `CoreHunter`.

I had also not finished the API. It's not yet possible to actually specify a custom seed generator. We should add an argument `long seed` to both `sampleCore` and `normalizeObjectives` and use this to initialize the search seed generator.

**Comment by daveneti** [comment]
ok, I will continue on this route on this branch and then merge in to develop later. I would like to get this, #79 and #73 into version 3.2 for a release.

**Comment by hdbeukel** [comment]
When would you like to release 3.2? I am happy to help with these issues, but right now I don't really have the time---you know why :-)

**Comment by daveneti** [comment]
I think it will be a few weeks for the next release. I can do most of the coding. I will just need someone to check my work.

Guy

**Pull request merged**
