### PR TITLE
Feature/get matrix data

### PR DESCRIPTION
**Pull request by daveneti**

### CODE REVIEW

**Comment by daveneti** [comment]
Hi @hdbeukel can you please check why travis is failing? It seems to be killed, but I am not sure why?

**Comment by hdbeukel** [comment]
I reran the checks but they were killed on the same test so I will try to find out why.

**Comment by hdbeukel** [comment]
Strange, the checks run fine on my laptop...

**Comment by hdbeukel** [comment]
It seems to be a Travis issue which you may be able to solve by increasing the memory of the VM used by the surefire plugin. See

 - http://stackoverflow.com/questions/23260057/the-forked-vm-terminated-without-saying-properly-goodbye-vm-crash-or-system-exi 
 - https://issues.jboss.org/browse/RF-13996

**Comment by daveneti** [comment]
It also compile with no issues on my laptop. I will look into the memory issues.

**Comment by daveneti** [comment]
It all seems to work now, merged in to develop.

**Pull request merged**
