### PR TITLE
Genotype data formats

### PR DESCRIPTION
**Pull request by hdbeukel**

### CODE REVIEW

**Comment by hdbeukel** [comment]
@daveneti Currently it is not possible to write diploid data to the same output format as the original input. The original data is not stored but converted to frequencies and cannot be converted back. Should I provide an extended format that stores the original data so that it can be written? (like for biallelic data)

**Comment by daveneti** [comment]
Yes, I sort of already knew this already when I was looking at it at the w/e. At the moment I don't need it. I was thinking about solving this in a different way. I need the write method to save the data for CH to read later by CH. So actually I only need the write methods for the frequency and biallelic data. I don't need it at the moment for the services. I will store the file in the native format (by copying the file) and the converted format using the write method. The native format is needed because the users will expect to see the data the way they loaded it and the converted format is needed by CH. So in summary to answer your question. You can do it if you have time to create new classes for these new formats, or if you don't have time, please just throw an exception if the given format is not supported.

**Comment by hdbeukel** [comment]
Ok I will see. I added a method `getSupportedDataFormats` to the genotype variant data classes which may be useful in the GUI if the user can select the desired format. Specifying any other format than the supported ones throws an exception. Currently you can write general data to frequency format and biallelic data to both allele scores or frequency format.

**Comment by daveneti** [comment]
Thanks a lot. I am merging in your changes on a regular basis, so that I don't get too out of synch on the service-impl branch.

**Comment by hdbeukel** [comment]
I have added support for homozygous data and ploidy larger than two. This type of data (including diploid) is jointly referred to as phased data (see `GenotypeFormat.PHASED`). When reading phased data, the ploidy is automatically inferred based on the column naming convention that each column is tagged with the marker name, optionally followed by a suffix starting with `.`, `_` or `-`. It is allowed to have a varying number of columns per marker.

Currently only homozygous and diploid are tested. Phased data can still only be written to frequency format, since it is converted when reading the data. For now I will leave it as such but I will probably introduce an interface and class `(Simple)PhasedGenotypeVariantData` later.

**Comment by daveneti** [comment]
We should think of a better term than 'phased' (please see my previous mail/comment) I will think about this and make some suggestions.

**Pull request merged**
