### PR TITLE
Feature/service impl

### PR DESCRIPTION
**Pull request by daveneti**
I merged develop into this branch so that I am not so far away from develop. Can you please double check to see I have not done anything silly, i will continue to commit to this branch.

### CODE REVIEW

**Comment by hdbeukel** [comment]
I don't see any immediate issues except that some tests in the services module fail. Do you want me to find out why or is this expected?

**Comment by daveneti** [comment]
Thanks a lot. Don't worry about the unit tests in the service I am going refactor a little and then fix the tests.

Do we meet on Wednesday? I don't have too much to discuss. I will not be able to show much more on the interface.

**Comment by hdbeukel** [comment]
Let's postpone the meeting then.

> Op 18 apr. 2016 om 18:17 heeft Guy Davenport <notifications@github.com> het volgende geschreven:
> 
> Thanks a lot. Don't worry about the unit tests in the service I am going refactor a little and then fix the tests.
> 
> Do we meet on Wednesday? I don't have too much to discuss. I will not be able to show much more on the interface.
>

**Comment by daveneti** [comment]
Ok, let's change it to the 27th.

**Comment by daveneti** [comment]
it is still failing on the genotype tests, I think the write method is not correct. @hdbeukel once you are finished with the read/write methods I will double check.

**Pull request merged**
